Fix subscription to use global tables instead of this.tables
Bug: subscription was calling this.tables.SyncControlState.get() but
SyncControlManager doesn't have a tables property, causing:
TypeError: Cannot read properties of undefined (reading 'SyncControlState')

Fix: Use global tables object declared at top of file instead of this.tables